sudo: required
dist: trusty
language: node_js
node_js:
- '10.15'
services:
- docker
branches:
  only:
  - master
  - deployment-test
  - 06-testing-and-ci-cd-live
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@$(node -p "require('./package').engines.npm")
install:
- npm install
before_script:
- sudo service postgresql stop
- docker-compose up -d
- docker ps
script:
- npm run lint
- npm test
after_success:
env:
  global:
  - NODE_ENV=test
  - DB_URI=postgres://postgres:testpasswd@127.0.0.1:5433/nodejsnights-db-tests
before_deploy:
- rm -rf node_modules
